on:
  push:
    branches:
      - master

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure node environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Lint code
        run: yarn lint

  deploy:
    name: Deploy
    needs: [lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure node environment
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: yarn install

      - name: Build app for production
        run: yarn generate
        env:
          BASE_URL: https://api.feedbank.tech
          NUXT_ENV_API_ROUTE: /api/v1
          NUXT_HOST: https://feedbank.tech
          NUXT_PORT: 80
          NUXT_ENV_RECAPTCHA_SITE_KEY: '6Lf7dHsaAAAAAMtaoxgXj-54u9QnvkD_1ynoMoVx'
          NUXT_ENV_WS_HOST: 'ws.feedbank.tech'
          NUXT_ENV_WS_PORT: 443

      - name: Copy deployment configuration
        run: cp ./.appengine/app.yaml ./dist

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to App Engine
        run: gcloud app deploy --version 1 --quiet --promote ./dist
